[package]
name = "brotherget-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
error-chain = "0.12.4"
futures = "0.3.18"
indicatif = "0.16.2"